name: go_ride_sharing
description: "Go Ride Share: Carpool smarter, save money, and drive green."

# keep this to prevent accidental publishing to pub.dev
# pub.dev is where you find useful Flutter packages
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`.
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  crypto: ^3.0.5
  shared_preferences: any
  equatable: any
  image_picker: any


dev_dependencies:
  flutter_test:
    sdk: flutter

  # contains a set of recommended lints to encourage good coding practices. 
  # See `analysis_options.yaml` file for specific lint rules
  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/styles/
  fonts:
    - family: Custom
      fonts:
        - asset: assets/fonts/CaviarDreams_Bold.ttf
          weight: 700
        - asset: assets/fonts/CaviarDreams_Italic.ttf
          style: italic
        - asset: assets/fonts/CaviarDreams_BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/CaviarDreams.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
